const nodemailer = require("nodemailer");

let transporter;

try {
  transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  // Non-blocking verification — log result but don't crash
  transporter.verify()
    .then(() => console.log("✅ Email transporter ready"))
    .catch((err) => console.error("⚠️  Email auth failed (emails won't send):", err.message));
} catch (err) {
  console.error("⚠️  Email transporter creation failed:", err.message);
}

async function sendEmail(recipient, summary, fileName) {
  if (!transporter) {
    throw new Error("Email transporter not configured");
  }

  const subjectLine = fileName
    ? `Your Analysis Report — ${fileName}`
    : "Your Dataset Analysis Report";

  const htmlBody = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; padding: 32px; background-color: #0a0a0b; color: #e4e4e7;">
      <div style="border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 24px; margin-bottom: 24px;">
        <h1 style="font-size: 20px; font-weight: 600; color: #ffffff; margin: 0 0 4px 0;">InsightFlow</h1>
        <p style="font-size: 13px; color: #a1a1aa; margin: 0;">AI-Powered Dataset Analysis</p>
      </div>
      ${fileName ? `<p style="font-size: 13px; color: #a1a1aa; margin-bottom: 16px;">Report for: <strong style="color: #e4e4e7;">${fileName}</strong></p>` : ""}
      <div style="background-color: #141416; border: 1px solid rgba(255,255,255,0.08); border-radius: 8px; padding: 24px; white-space: pre-wrap; line-height: 1.7; font-size: 14px; color: #d4d4d8;">
${summary}
      </div>
      <p style="font-size: 12px; color: #71717a; margin-top: 24px; text-align: center;">Generated by InsightFlow &bull; AI-powered dataset summarization</p>
    </div>
  `;

  const info = await transporter.sendMail({
    from: `"InsightFlow" <${process.env.EMAIL_USER}>`,
    to: recipient,
    subject: subjectLine,
    html: htmlBody,
    text: summary,
  });

  console.log("📧 Email sent:", info.messageId, "to:", recipient);
}

module.exports = sendEmail;